[package]
name = "gpu-raytracing"
edition = "2021"
rust-version = "1.88"
publish = false

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11"
pollster = "0.4"
wgpu = "27.0.0"

anyhow = "1.0"
winit = "0.30"
log = "0.4"
